### ISSUE TITLE
大佬不好意思又打扰你一次了，在lab08那个递增子序列的问题中，我想不出他的状态转移方程，大佬能说一下他们的规律是什么吗？

### ISSUE THREAD

**Issue by Unic-hou** [chenyuxiang0425/cs61a_sp20#2]

**Comment by chenyuxiang0425** [comment]
这我好像没用动态规划做，用树递归做的。

**Comment by chenyuxiang0425** [comment]
你现在会了没，需要我说一下树递归的做法吗

**Comment by chenyuxiang0425** [comment]
`def subseq_helper(s, prev):` 返回一个递增子序列，并且子序列中所有的值都 >= prev
那么`subseq_helper`返回的`list`只可能包含两种情况
- 包含 s[0] 和 不包含 s[0]
  - 比如[1,3,2] 对应的所有子序列，包含 s[0] 是 a，不包含 s[0] 是 b。
    - a= [[1, 3], [1, 2], [1]]  
    - b= [[3], [2], []]
- 然后考虑这两种情况的实现方法
  - b 很简单，把 s 变成 s[1:] 就可以
  - a 的情况稍微复杂一点
    - 先得要个子序列（该子序列不包括s[0]）中所有的值都 >= s[0] 的情况
      - 比如  [[1, 3], [1, 2], [1]]  得先要个 [[3],[2],[]]
      - 比如 [[1, 2, 3], [1,2], [1,3], [1]] 得先要个 [[2, 3], [2], [3], []]
    - 然后把 s[0] 插入这个子序列内列表的所有的开头

**Comment by Unic-hou** [comment]
懂了，谢谢大佬！

**Comment by Unic-hou** [comment]
大佬，我还有个疑问，既然a是先取得子序列，不插入s[0]时等价于b,那为什么a=sub(s[1:],s[0])而b=sub(s[1:],prev)呢？

**Comment by chenyuxiang0425** [comment]
这两个不等价噢，一个是为了满足配合 s[0] 而建的子序列，另一个是只要满足不包含 s[0] 就成立的子序列。
好比原始列表是 [2,1,3]，那么
- `sub(s[1:],s[0]) = [[3], []]`
- `sub(s[1:],prev) = [[1, 3], [1], [3], []]`

**Comment by Unic-hou** [comment]
这次真懂了，我的描述一开始可能有点问题，我觉得状态转移方程就只是表示他们之间f(i)和f(i-1)的关系的，我不知道是专指动态规划的
